[project]
name = "comfyui"
version = "0.0.0"
requires-python = "==3.12.*"
dependencies = [
  # https://github.com/Comfy-Org/ComfyUI/blob/52976f3ea33cc2312c7b5a32e1c7510b203eefb6/requirements.txt
  "comfyui-frontend-package==1.43.18",
  "comfyui-workflow-templates==0.9.73",
  "comfyui-embedded-docs==0.4.4",
  "torch",
  "torchsde",
  "torchvision",
  "torchaudio",
  "numpy>=1.25.0",
  "einops",
  "transformers>=4.50.3",
  "tokenizers>=0.13.3",
  "sentencepiece",
  "safetensors>=0.4.2",
  "aiohttp>=3.11.8",
  "yarl>=1.18.0",
  "pyyaml",
  "Pillow",
  "scipy",
  "tqdm",
  "psutil",
  "alembic",
  "SQLAlchemy>=2.0.0",
  "filelock",
  "av>=14.2.0",
  "comfy-kitchen>=0.2.8",
  "comfy-aimdo==0.3.0",
  "requests",
  "simpleeval>=1.0.0",
  "blake3",
  "kornia>=0.7.1",
  "spandrel",
  "pydantic~=2.0",
  "pydantic-settings~=2.0",
  "PyOpenGL",
  "glfw",
]

[tool.uv]
package = false
exclude-newer = "P7D"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }
